#!/usr/bin/env bash
# prime_focus_f36_meancos: run_prime_focus_f36.sh with the mirror figure FROZEN
# to the fixed astigmatic candidate: the cos(AOI)-weighted year-mean figure
# (data/fixed_shapes_pf36000_mean_cos.csv, generated by
# scripts/build_fixed_shapes.py). Pointing still tracks. See the f36 script's
# header for the scenario family and every other decision.
# Requires the `sweep --fixed-shapes` option (fails cleanly if not yet landed).

set -u

REPO="C:/gitlab/heliostats"
NAME="prime_focus_f36_meancos"
SHAPES="data/fixed_shapes_pf36000_mean_cos.csv"
OUT="analysis_output/$NAME"
LOG="$REPO/analysis_output/$NAME.log"
LOCKDIR="$REPO/analysis_output/.$NAME.lock"

cd "$REPO" || exit 1
say() { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG"; }

if [ ! -f "$SHAPES" ]; then
    say "$SHAPES does not exist -- run scripts/build_fixed_shapes.py first. NOT starting."
    exit 1
fi

if ! mkdir "$LOCKDIR" 2>/dev/null; then
    say "another run holds $LOCKDIR -- exiting"
    exit 0
fi
trap 'rm -rf "$LOCKDIR"' EXIT   # rm -rf, not rmdir: the lock holds a pid file
echo "$$" > "$LOCKDIR/pid"

say "starting $NAME (4-day sample, F1 36000, FIXED astig figure, cos(AOI)-weighted year mean), pid $$"
python -u -m beamdown sweep \
    --secondary prime_focus \
    --focus-height-mm 36000 \
    --n-mirrors 1 \
    --model-file models/heliostat_field_prime_focus.optx \
    --fixed-shapes "$SHAPES" \
    --all-heliostats \
    --dates 2026-12-21 2026-02-20 2026-04-21 2026-06-21 \
    --rays 120000 \
    --rays-per-trace 120000 \
    --workers 1 \
    --output "$OUT" 2>&1 | tee -a "$LOG"
status=${PIPESTATUS[0]}

if [ "$status" -ne 0 ]; then
    say "$NAME exited with status $status"
    exit "$status"
fi

say "$NAME complete -- annual energy"
python -u scripts/report_energy.py --run "$OUT" 2>&1 | tee -a "$LOG"
say "done"
